### ISSUE TITLE
Nothing is recognized as TV shows, everything is movies

### ISSUE THREAD

**Issue by aibradford** [vorghahn/iptv4plex#10]
I know there are limitations, but iptv4plex is only recognizing everything as movies. 

I had to use xtream editor to cut down on the amount of channels so iptv4plex would load properly, so im wondering if going through xtream editor somehow is confusing plex and making it think EVERYTHING is movies, when most of the stuff is not.

It is picking up one channel as TV shows only, out of 271 channels. So it can tell the difference, but only for this one channel from New Zealand.

Im not sure if this is an issue with my IPTV providers EPG info or what?  I just cant make sense of this?

Any help?

**Comment by vorghahn** [comment]
AFAIK this is issue #8 already.

Can you add your specific channel details into that issue and then close this please?
