### ISSUE TITLE
Wrong number of tuners

### ISSUE THREAD

**Issue by warham28** [vorghahn/iptv4plex#15]
Hello,

i have a problem .. with the windows version...

if i put Tunerlimits to 1... 

 Plex Media server see : 49 tuners... 

  "BaseURL": "http://192.168.2.45:5004/1", 
  "DeviceAuth": "test12341", 
  "DeviceID": "123456781", 
  "FirmwareName": "hdhomeruntc_atsc", 
  "FirmwareVersion": "20150826", 
  "FriendlyName": "iptv4plex1", 
  "LineupURL": "http://192.168.2.45:5004/1/lineup.json", 
  "Manufacturer": "Silicondust", 
  "ModelNumber": "HDTC-2US", 
  "TunerCount": "1"

{"m3u8url": "c:\\channels1.m3u;", "port": 5004, "ffmpegloc": "C:\\ffmpeg\\bin\\ffmpeg.exe", "xmlurl": ";", "tunerlimits": "1;", "ip": "192.168.2.45"}

You have an idea?

**Comment by warham28** [comment]
it seem to be in the tunercount on the device info..

we see "TunerCount": "1" and the right syntax supposed to be "TunerCount": 1 no?

**Comment by vorghahn** [comment]
I believe it's meant to be an integer and not a string. Pushing an update out now.

**Comment by warham28** [comment]
Thanks! :)

**Comment by vorghahn** [comment]
Let me know if it fixes it please.

**Comment by warham28** [comment]
Well.. not fixes...


Plex Media Server info : 


iptv4plex1
192.168.2.45:5004/1
49 channels
Chaîne 403—

{
"BaseURL": "http://192.168.2.45:5004/1",
"DeviceAuth": "test12341",
"DeviceID": "123456781",
"FirmwareName": "hdhomeruntc_atsc",
"FirmwareVersion": "20150826",
"FriendlyName": "iptv4plex1",
"LineupURL": "http://192.168.2.45:5004/1/lineup.json",
"Manufacturer": "Silicondust",
"ModelNumber": "HDTC-2US",
"TunerCount": 1
}

{"xmlurl": ";;;", "tunerlimits": "1;1;1;1", "port": 5004, "m3u8url": "c:\\channels.m3u;c:\\channels1.m3u;c:\\channels2.m3u;c:\\tv_channels_Mathieu4.m3u", "ffmpegloc": "C:\\ffmpeg\\bin\\ffmpeg.exe", "ip": "192.168.2.45"}

**Comment by warham28** [comment]
Channels menu is http://192.168.2.45:5004
Combined m3u8 url is http://192.168.2.45:5004/playlist.m3u8
EPG url is http://192.168.2.45:5004/epg.xml
Plex Live TV combined url is http://192.168.2.45:5004
Plex Live TV single tuner url for c:\channels.m3u is http://192.168.2.45:5004/1
Plex Live TV single tuner url for c:\channels1.m3u is http://192.168.2.45:5004/2
Plex Live TV single tuner url for c:\channels2.m3u is http://192.168.2.45:5004/3
Plex Live TV single tuner url for c:\tv_channels_Mathieu4.m3u is http://192.168.2.45:5004/4
Donations: PayPal to vorghahn.sstv@gmail.com  or BTC - 19qvdk7JYgFruie73jE4VvW7ZJBv8uGtFb
##############################################################

2018-08-20 00:19:11,511 - INFO       - iptv4plex  -  <module>                 - Your version (0.3) is up to date.
2018-08-20 00:19:11,511 - INFO       - iptv4plex  -  <module>                 - Listening on 192.168.2.45:5004 at http://192.168.2.45:5004/
2018-08-20 00:19:36,790 - INFO       - iptv4plex  -  sub_tuners               - 1/discover.json was requested by 192.168.2.45
2018-08-20 00:19:36,793 - INFO       - iptv4plex  -  sub_tuners               - 1/lineup_status.json was requested by 192.168.2.45
2018-08-20 00:19:36,804 - INFO       - iptv4plex  -  sub_tuners               - 1/discover.json was requested by 192.168.2.45
2018-08-20 00:19:36,816 - INFO       - iptv4plex  -  sub_tuners               - 1/lineup_status.json was requested by 192.168.2.45
2018-08-20 00:19:37,718 - INFO       - iptv4plex  -  sub_tuners               - 1/lineup.json was requested by 192.168.2.45
2018-08-20 00:19:41,759 - INFO       - iptv4plex  -  sub_tuners               - 1/lineup.json was requested by 192.168.2.45
2018-08-20 00:22:25,464 - INFO       - iptv4plex  -  sub_tuners               - 1/lineup.json was requested by 192.168.2.45
2018-08-20 00:23:08,160 - INFO       - iptv4plex  -  sub_tuners               - 1/discover.json was requested by 192.168.2.45
2018-08-20 00:27:09,904 - INFO       - iptv4plex  -  <module>                 - Finished!

**Comment by warham28** [comment]
if i take the discover for telly ... 

{
"FriendlyName":"HDHomerun (telly)",
"Manufacturer":"Silicondust",
"ModelNumber":"HDTC-2US",
"FirmwareName":"hdhomeruntc_atsc",
"TunerCount":1,
"FirmwareVersion":"20150826",
"DeviceID":"22345678",
"DeviceAuth":"telly123",
"BaseURL":"http://127.0.0.1:6077",
"LineupURL":"http://127.0.0.1:6077/lineup.json"
}

And for Xteve 

{
  "BaseURL": "192.168.2.45:34400",
  "DeviceAuth": "xteve",
  "DeviceID": "2018-08-6EF1-ZU0VDL",
  "FirmwareName": "bin_1.0.1",
  "FirmwareVersion": "1.0.1",
  "FriendlyName": "xTeVe",
  "LineupURL": "192.168.2.45:34400/lineup.json",
  "Manufacturer": "golang",
  "ModelNumber": "1.0.1",
  "TunerCount": 1
}

**Comment by vorghahn** [comment]
Sorry, I'm not sure I see what's wrong now!

What is wrong?

**Comment by warham28** [comment]
Well, plex see the tuner can play 49 stream at the same time... even if i say 1 stream at the time....

**Comment by vorghahn** [comment]
49 Channels means it can see 49 channels, not play 49 at once.
Have you tried playing more than one stream at a time?

**Comment by warham28** [comment]
Well if i try to play 2 stream simultaneous  ... plex will allowed it even if i say only 1 stream ... 

Well i see it in french but if you prefer... Plex see 49 tuners for only one instance of iptv4plex

**Comment by vorghahn** [comment]
Ok so i have confirmed it is working as intended currently. refer https://imgur.com/tu9ZzTr

Now if you have changed your tuner limits then you will need to reinstall the tuner.

Tuner limits are only in effect for individual tuners so you'll need to set up your dvr using :
http://127.0.0.1:6077/1

Though I'd recommend using 5004 as the port as there were times when plex would only support 80/5004 ports, I can't remember why though.
